/**
 * MERCHANDISE — what the /store page features once the shop is open.
 *
 * The shop itself (checkout, sizes, shipping, payment) lives on Printify; this
 * file only decides what the family's own site points at. Nothing here shows
 * until MERCH_STOREFRONT_URL is set in Vercel (see lib/merch.ts and
 * docs/PRINTIFY-SETUP.md).
 *
 * Print-ready artwork for the first four designs is in merch/designs/,
 * generated by `npx tsx scripts/merch-designs.tsx`.
 */

export type MerchProduct = {
  name: string;
  /** Price exactly as the shop lists it, e.g. "$24.99". */
  price: string;
  /** Product page on the storefront. Must be on the storefront's host. */
  url: string;
  /** Mockup image URL from the shop (Printify serves these publicly). */
  image?: string;
};

export const merch = {
  /**
   * Where the profit goes — ONLY once Don has decided it, in words he
   * approves (e.g. "Profit from every shirt goes to the Malawi water well").
   * Empty string shows nothing. Never guess this line.
   */
  proceeds: "",
  /** Up to six featured products. Empty shows the plain "Shop" button only. */
  products: [] as MerchProduct[],
};
